version: '3.7'

services:

  web:
    build:
      context: .
    env_file:
      - .env
    command: bash -c "sleep 1000000"
    volumes:
      - ./:/usr/src/app
      - gems:/usr/local/bundle
      - node-modules:/usr/src/app/node_modules
    ports:
      - 3000:3000

volumes:
  gems:
  node-modules:
