 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cloud_stacks", type: :request do
  # CloudStack. As you add validations to CloudStack, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CloudStack.create! valid_attributes
      get cloud_stacks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cloud_stack = CloudStack.create! valid_attributes
      get cloud_stack_url(cloud_stack)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cloud_stack_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      cloud_stack = CloudStack.create! valid_attributes
      get edit_cloud_stack_url(cloud_stack)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CloudStack" do
        expect {
          post cloud_stacks_url, params: { cloud_stack: valid_attributes }
        }.to change(CloudStack, :count).by(1)
      end

      it "redirects to the created cloud_stack" do
        post cloud_stacks_url, params: { cloud_stack: valid_attributes }
        expect(response).to redirect_to(cloud_stack_url(CloudStack.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CloudStack" do
        expect {
          post cloud_stacks_url, params: { cloud_stack: invalid_attributes }
        }.to change(CloudStack, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post cloud_stacks_url, params: { cloud_stack: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cloud_stack" do
        cloud_stack = CloudStack.create! valid_attributes
        patch cloud_stack_url(cloud_stack), params: { cloud_stack: new_attributes }
        cloud_stack.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cloud_stack" do
        cloud_stack = CloudStack.create! valid_attributes
        patch cloud_stack_url(cloud_stack), params: { cloud_stack: new_attributes }
        cloud_stack.reload
        expect(response).to redirect_to(cloud_stack_url(cloud_stack))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cloud_stack = CloudStack.create! valid_attributes
        patch cloud_stack_url(cloud_stack), params: { cloud_stack: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cloud_stack" do
      cloud_stack = CloudStack.create! valid_attributes
      expect {
        delete cloud_stack_url(cloud_stack)
      }.to change(CloudStack, :count).by(-1)
    end

    it "redirects to the cloud_stacks list" do
      cloud_stack = CloudStack.create! valid_attributes
      delete cloud_stack_url(cloud_stack)
      expect(response).to redirect_to(cloud_stacks_url)
    end
  end
end
