 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/compliances", type: :request do
  # Compliance. As you add validations to Compliance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Compliance.create! valid_attributes
      get compliances_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      compliance = Compliance.create! valid_attributes
      get compliance_url(compliance)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_compliance_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      compliance = Compliance.create! valid_attributes
      get edit_compliance_url(compliance)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Compliance" do
        expect {
          post compliances_url, params: { compliance: valid_attributes }
        }.to change(Compliance, :count).by(1)
      end

      it "redirects to the created compliance" do
        post compliances_url, params: { compliance: valid_attributes }
        expect(response).to redirect_to(compliance_url(Compliance.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Compliance" do
        expect {
          post compliances_url, params: { compliance: invalid_attributes }
        }.to change(Compliance, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post compliances_url, params: { compliance: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested compliance" do
        compliance = Compliance.create! valid_attributes
        patch compliance_url(compliance), params: { compliance: new_attributes }
        compliance.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the compliance" do
        compliance = Compliance.create! valid_attributes
        patch compliance_url(compliance), params: { compliance: new_attributes }
        compliance.reload
        expect(response).to redirect_to(compliance_url(compliance))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        compliance = Compliance.create! valid_attributes
        patch compliance_url(compliance), params: { compliance: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested compliance" do
      compliance = Compliance.create! valid_attributes
      expect {
        delete compliance_url(compliance)
      }.to change(Compliance, :count).by(-1)
    end

    it "redirects to the compliances list" do
      compliance = Compliance.create! valid_attributes
      delete compliance_url(compliance)
      expect(response).to redirect_to(compliances_url)
    end
  end
end
